include /tmp/iperf-2.0.5/Android.mk
include /tmp/iperf-2.0.10/Android.mk
include /tmp/iperf-2.0.11/Android.mk
include /tmp/iperf-2.0.12/Android.mk
include /tmp/iperf-2.0.13/Android.mk
include /tmp/iperf-2.1.3/Android.mk
include /tmp/iperf-2.1.4/Android.mk

include /tmp/iperf-3.1.6/Android.mk
include /tmp/iperf-3.1.7/Android.mk
include /tmp/iperf-3.2/Android.mk
include /tmp/iperf-3.2rc1/Android.mk
include /tmp/iperf-3.3/Android.mk
include /tmp/iperf-3.4/Android.mk
include /tmp/iperf-3.5/Android.mk
include /tmp/iperf-3.6/Android.mk
include /tmp/iperf-3.7/Android.mk
include /tmp/iperf-3.8/Android.mk
include /tmp/iperf-3.8.1/Android.mk
include /tmp/iperf-3.9/Android.mk
include /tmp/iperf-3.10/Android.mk
include /tmp/iperf-3.10.1/Android.mk
