include /tmp/iperf-3.1.6/Android.mk
include /tmp/iperf-3.1.7/Android.mk
include /tmp/iperf-3.2/Android.mk
include /tmp/iperf-3.2rc1/Android.mk
include /tmp/iperf-3.3/Android.mk
include /tmp/iperf-3.4/Android.mk
include /tmp/iperf-3.5/Android.mk
include /tmp/iperf-3.6/Android.mk
include /tmp/iperf-3.7/Android.mk
